name: deleteOldWorkflow

on:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  delete-old-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 15