name: deleteOldWorkflow

on:
  schedule:
    - cron: '0 15 15 * *'
  workflow_dispatch:

jobs:
  delete-old-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 15
          keep_minimum_runs: 0
      
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 失敗しました
          SlACK_MESSAGE:  Actions URLからエラーを確認してください
          SLACK_USERNAME: failure actions url
          SLACK_WEBHOOK: ${{ secrets.NOTIFY_FAILURE_SLACK_URL }}