name: deploy

on:
  #プルリクがmainブランチにマージされた時がイベント
  pull_request:
    types:
      - closed
    branches:    
      - 'main'
  workflow_dispatch:
    branches:
      - main
jobs:
  S3-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #アクションとして他ディレクトリに配置し
      #ここからusesで使うようにする
      - name: create packages
        run: mkdir -v packages
      - name: ready zip dir
        run: cd ./packages
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: cp
        run: cp ../lambda_function.py lambda_function.py
      - name: pip install
        run: pip install -r ../require.text -t ./

      - name: create zip
        run: zip -r main.zip packages/* 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: upload main.zip to s3
        run: aws s3 cp main.zip s3://levelupgeek

  Lambda-deploy:
    needs: S3-upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #公式からバージョンを確認する。https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: update Lambda function
        run: |
          aws lambda update-function-code --function-name LineBot --s3-bucket levelupgeek --s3-key main.zip\
          | jq '.FunctionName, .LastUpdateStatus'
     