name: deploy

on:
  #プルリクがmainブランチにマージされた時がイベント
  pull_request:
    types:
      - closed
    branches:    
      - 'main'
  workflow_dispatch:
    branches:
      - main

jobs:
  Zip-create:
    runs-on: windows-2022
    
    steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
       
       - name: download-access_token
         id: download-access_token
         uses: ./.github/actions/download-s3-object
         with:
          s3-object: 'access_token.json'
   
       - name: set-access_token
         run: echo ::set-env name=ACCESS_TOKEN::$(echo ${{ toJSON(steps.download-access_token.outputs.s3-object) }} | jq -r -R  'fromjson? | .access_token')

       - name: create env and write secret information
         run: | 
          New-Item .env
          echo $ACCESS_TOKEN > .env

       - name: create packages and pip install and cp lambda_function.py, .env and create zip lambda_function
         run: |
          mkdir packages
          pip install -r ./requirements/prod.txt -t ./packages/
          cp lambda_function.py packages/
          cp .env packages/
          compress-archive packages/* lambda_function
        
      #windowsでzipにするー＞packagesディレクトリを含まず圧縮できる。
       - name: Upload lambda_function.zip for Zip-create
         uses: actions/upload-artifact@v3
         with:
          name: lambda_function
          path: lambda_function.zip
  
  S3-upload:
    runs-on: ubuntu-latest
    needs: Zip-create

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download lambda_function.zip for Zip-create
        uses: actions/download-artifact@v3
        with:
          name: lambda_function

      - name: cat lambda_function.zip
        run: zipinfo lambda_function.zip
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: upload lambda_function.zip to s3
        run: aws s3 cp lambda_function.zip s3://levelupgeek

  Lambda-deploy:
    needs: S3-upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: update Lambda function
      #不要な情報を出力しないようにフィルタリングする
        run: |
          aws lambda update-function-code --function-name LineBot --s3-bucket levelupgeek --s3-key lambda_function.zip\
          | jq '.FunctionName, .LastUpdateStatus'
     