name: deploy

on:
  #プルリクがmainブランチにマージされた時がイベント
  pull_request:
    types:
      - closed
    branches:    
      - 'main'
  workflow_dispatch:
    branches:
      - main
jobs:
  S3-upload:
    runs-on: ubuntu-latest

    steps:
    #v3がでていた。変えた方がいいかも
      - name: Checkout
        uses: actions/checkout@v2

      - name: create packages and pip install and  create zip lambda_function
        run: |
          mkdir -v packages
          pip install -r ./requirements.txt -t ./packages/
          zip lambda_function.zip lambda_function.py
      
      #packagesディレクトリを含まないように。
      #それが、できない、、、
      - name: create zip library  
        run: zip -ru ./lambda_function.zip ./packages/* 
      
      - name: cat lambda_function.zip
        run: zipinfo lambda_function.zip
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: upload lambda_function.zip to s3
        run: aws s3 cp lambda_function.zip s3://levelupgeek

  Lambda-deploy:
    needs: S3-upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: update Lambda function
      #不要な情報を出力しないようにフィルタリングする
        run: |
          aws lambda update-function-code --function-name LineBot --s3-bucket levelupgeek --s3-key lambda_function.zip\
          | jq '.FunctionName, .LastUpdateStatus'
     